# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: circleci/node:8.11
      - image: circleci/mongo:4-ram

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - run: yarn test:coverage
      - run: |
          if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
            git config --global push.default simple
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            yarn docs:publish
          fi