# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
branches:
  ignore:
    - gh-pages
jobs:
  build:
    docker:
      - image: circleci/node:8.11
      - image: circleci/mongo:4-ram

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn build
      - run: -[[ "${CIRCLE_BRANCH}" == "master" ]] && yarn test:coverage
      - run: -[[ "${CIRCLE_BRANCH}" == "master" ]] && yarn docs:publish